version: '3.8'

services:
  server:
    container_name: server
    build:
      context: ./back
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    env_file:
      - .env_mysql
    depends_on:
      - db
    volumes:
      - type: bind
        source: . 
        target: /src
      - type: bind
        source: .git
        target: /src/.git
    networks:
      - golang_test_network

  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    tty: true
    platform: linux/x86_64
    ports:
      - 3306:3306
    env_file:
      - .env_mysql
    volumes:
      - type: volume
        source: mysql_test_volume
        target: /var/lib/mysql
      - ./db/migration:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - golang_test_network

volumes:
  mysql_test_volume:
    name: mysql_test_volume

networks:
  golang_test_network:
    external: true