name: vulns
on:
  push:
  pull_request:
jobs:
  vulns:
    name: Vulnerability scanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.20
      - name: Download dependencies
        run: go mod download github.com/stretchr/testify
        working-directory: back
      - name: WriteGoList
        run: go list -json -m all > go.list
        working-directory: back
      - name: Nancy
        uses: sonatype-nexus-community/nancy-github-action@main
        with:
         nancyCommand: "cd back && nancy go.list"