name: vulns
on:
  push:
  pull_request:
jobs:
  vulns:
    name: Vulnerability scanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.20
        working-directory: back
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
        working-directory: back
      - name: Run golangci-lint
         run: golangci-lint run
        working-directory: back