name: Docker Compose Test
on:
  push:
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@v1

      - name: Run Docker Compose
        run: |
          docker compose up -d
          docker compose run server go test -v ./...