name: lint
on:
  push:
    branches:
      - master
      - develop
  pull_request:

permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.20
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

          # skip-build-cache: true

      - name: testing
        run: go test -shuffle on ./...